modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/Flan/issues"
[[mixins]]
config = "flan.mixins.json"
[[mixins]]
config = "flan.forge.mixins.json"
[[mods]] 
modId="flan"
version="${version}"
displayName="Flan"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Flan (Forge version): A serverside claiming mod'''
[[dependencies.flan]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.flan]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
